var RemoteDataEvent =
{
	"REQUEST_SUCCESS": "REQUEST_SUCCESS",
	"IDLE": "IDLE",
	"REQUEST_BEGUN": "REQUEST_BEGUN",
	"REQUEST_FAIL": "REQUEST_FAIL",
	"REQUEST_QUEUEING": "REQUEST_QUEUEING",
	"REQUEST_QUEUED": "REQUEST_QUEUED",
	"LAST_PAGE_REACHED": "LAST_PAGE_REACHED",
	"LAST_RECORD_REACHED": "LAST_RECORD_REACHED",
	"FIRST_PAGE_REACHED": "FIRST_PAGE_REACHED",
	"FIRST_RECORD_REACHED": "FIRST_RECORD_REACHED",
	"CURRENT_RECORD_CHANGED": "CURRENT_RECORD_CHANGED",
	"CURRENT_PAGE_CHANGED": "CURRENT_PAGE_CHANGED"
};