
import { StringUtils } from "/flowerui/lib/StringUtils.js";
import { ArrayUtils } from "/flowerui/lib/ArrayUtils.js";
import { RemoteArray } from "/flowerui/lib/rca/RemoteArray.js";
import { ArrayEx } from "/flowerui/lib//ArrayEx.js";
import { Component } from "/flowerui/components/base/Component.js";
import { Parent } from "/flowerui/components/base/Parent.js";
import { BrowserWindow } from "/flowerui/components/base/BrowserWindow.js";
import { NavParent } from "/flowerui/components/base/NavParent.js";
import { ViewStack } from "/flowerui/components/base/ViewStack.js";
import { Label } from "/flowerui/components/Label.js";
import { Button } from "/flowerui/components/Button/Button.js";
import { Container } from "/flowerui/components/Container.js";
import { Heading } from "/flowerui/components/Heading.js";

import { App } from "/flowerui/components/base/App.js";
import { Applet } from "/flowerui/components/base/Applet.js";
import { Cache } from "/flowerui/lib/cache/Cache.js";
import { BrowserManager } from "/flowerui/lib/BrowserManager.js";

import { TextInput } from "/flowerui/components/TextInput/TextInput.js";
import { Form } from "/flowerui/components/Form/Form.js";
import { FormField } from "/flowerui/components/Form/FormField.js";
import { Hidden } from "/flowerui/components/Form/Hidden.js";
import { HRule } from "/flowerui/components/HRule.js";
import { Br } from "/flowerui/components/Br.js";
import { Color } from "/flowerui/components/Color.js";
import { Nav } from "/flowerui/components/Nav.js";
import { Header } from "/flowerui/components/Header.js";
import { Footer } from "/flowerui/components/Footer.js";
import { Section } from "/flowerui/components/Section.js";
import { Link } from "/flowerui/components/Link/Link.js";
import { Repeater } from "/flowerui/components/Repeater/Repeater.js";
import { RepeaterEx } from "/flowerui/components/Repeater/RepeaterEx.js";
import { List } from "/flowerui/components/List.js";
import { CheckBox } from "/flowerui/components/CheckBox.js";
import { CheckBoxEx } from "/flowerui/components/CheckBoxEx.js";
import { CheckBoxGroup } from "/flowerui/components/CheckBoxGroup.js";
import { RadioButton } from "/flowerui/components/RadioButton.js";
import { RadioGroup } from "/flowerui/components/RadioGroup.js";
import { Toggle } from "/flowerui/components/Toggle/Toggle.js";
import { Amount } from "/flowerui/components/Amount.js";
import { Image } from "/flowerui/components/Image.js";
import { TextArea } from "/flowerui/components/TextArea.js";
import { Option } from "/flowerui/components/Select/Option.js";
import { Select } from "/flowerui/components/Select/Select.js";
import { DropDown } from "/flowerui/components/DropDown/DropDown.js";
import { Li } from "/flowerui/components/Tree/Li.js";
import { Tree } from "/flowerui/components/Tree/Tree.js";
import { DateTime } from "/flowerui/components/DateTime/DateTime.js";
import { DateCmp } from "/flowerui/components/DateTime/DateCmp.js";
import { Time } from "/flowerui/components/DateTime/Time.js";
import { SideNav } from "/flowerui/components/SideNav/SideNav.js";
import { Modal } from "/flowerui/components/Modal/Modal.js";
import { Upload } from "/flowerui/components/Form/Upload.js";
import { UploadEx } from "/flowerui/components/UploadEx.js";
import { MultiUpload } from "/flowerui/components/MultiUpload.js";
import { Table } from "/flowerui/components/Table/Table.js";
import { TBody } from "/flowerui/components/Table/TBody.js";
import { THead } from "/flowerui/components/Table/THead.js";
import { TFoot } from "/flowerui/components/Table/TFoot.js";
import { TCell } from "/flowerui/components/Table/TCell.js";
import { Tr } from "/flowerui/components/Table/Tr.js";
import { Th } from "/flowerui/components/Table/Th.js";
import { Td } from "/flowerui/components/Table/Td.js";
import { DataGridCellRenderer } from "/flowerui/components/DataGrid/DataGridCellRenderer.js";
import { DataGridColumn } from "/flowerui/components/DataGrid/DataGridColumn.js";
import { DataGrid } from "/flowerui/components/DataGrid/DataGrid.js";
import { ValidationManager } from "/flowerui/components/Validation/ValidationManager.js";
import { RangeValidator } from "/flowerui/components/Validation/RangeValidator.js";
import { DateRangeValidator } from "/flowerui/components/Validation/DateRangeValidator.js";
import { RequiredFieldValidator } from "/flowerui/components/Validation/RequiredFieldValidator.js";
import { RegularExpressionValidator } from "/flowerui/components/Validation/RegularExpressionValidator.js";
import { CustomValidator } from "/flowerui/components/Validation/CustomValidator.js";
import { AutoCompleteEx } from "/flowerui/components/AutoComplete/AutoCompleteEx.js";
import { DataBrowse } from "/flowerui/components/DataBrowse.js";
import { AutoBrowse } from "/flowerui/components/AutoBrowse.js";
import { TokenRenderer } from "/flowerui/components/AutoComplete/TokenRenderer.js";
import { SuggestionRenderer } from "/flowerui/components/AutoComplete/SuggestionRenderer.js";
import { ProgressBar } from "/flowerui/components/ProgressBar/ProgressBar.js";
import { Filter } from "/flowerui/components/Filter/Filter.js";
import { Calendar } from "/flowerui/components/Calendar/Calendar.js";
import { CalendarDay } from "/flowerui/components/Calendar/CalendarDay.js";
import { CalendarWeek } from "/flowerui/components/Calendar/CalendarWeek.js";
import { CalendarMonth } from "/flowerui/components/Calendar/CalendarMonth.js";

import { Env } from "/flowerui/lib/Env.js";
//import { DataView } from "/app/app/lib/DataView.js";
//import { GaiaAPI_utils } from "/app/app/lib/GaiaAPI_utils.js";
import { Wizard } from "/flowerui/components/wizard/Wizard.js";
import { History } from "/flowerui/components/base/History/History.js";
import { Timer } from "/flowerui/lib/Timer.js";
import { Loader } from "/flowerui/components/Loader.js";
import { BindingsManager } from "/flowerui/lib/binding/BindingsManager.js";
import { ChangeWatcher } from "/flowerui/lib/binding/ChangeWatcher.js";
import { LocalizationManager } from "/flowerui/lib/LocalizationManager.js";

import { DateUtils } from "/flowerui/lib/DateUtils.js";
window.DateUtils = DateUtils;
import { NumberUtils } from "/flowerui/lib/NumberUtils.js";
window.NumberUtils = NumberUtils;

import { oxana } from "/flowerui/oxana/forms/forms.js";
import { rjs } from "/flowerui/lib/rjs.js";
rjs.define("/flowerui/lib/dependencies/scripts/jquery.slimscroll.js");
rjs.define("/flowerui/lib/dependencies/summernote/summernote.css");
rjs.define("/flowerui/components/Calendar/css/calendarMonth-default.css");
rjs.define("/flowerui/components/Calendar/css/calendarWeek-default.css");
rjs.define("/flowerui/components/Calendar/css/calendarDay-default.css");
rjs.define("/flowerui/components/Calendar/css/calendar-default.css");
rjs.define('/flowerui/components/CreditCard/css/creditCard-default.css');
rjs.define("/flowerui/components/Repeater/css/repeater-default.css");
rjs.define("/flowerui/components/DataGrid/css/datagrid-default.css");
rjs.define("/flowerui/components/Toggle/toggle-default.css");
rjs.define("/flowerui/components/DateTime/css/dateTime_default.css");
rjs.define("/flowerui/components/AutoComplete/AutoCompleteEx.css");
rjs.define("/flowerui/components/base/css/parent-default.css");
rjs.define("/flowerui/components/base/css/collapse.css");
rjs.define("/flowerui/components/HierarchialTree/css/HierarchialTree-default.css");
rjs.define("/flowerui/components/SideNav/css/sidenav-default.css");
rjs.define("/flowerui/components/DropEdit/css/DropEdit.css");
rjs.define("/flowerui/components/Tree/css/tree-default.css");
rjs.define("/flowerui/components/SideNav/css/sideNav.css");
rjs.define("/flowerui/components/Kanban/css/kanban_default.css");
rjs.define("/flowerui/components/Filter/Filter.css");
rjs.define("/flowerui/oxana/forms/css/forms.css");
rjs.define("/flowerui/oxana/css/global.css");