var FiscalPrinterEventType = 
{
	"FISCAL_RECEIPT_RECEIVED":"FISCAL_RECEIPT_RECEIVED",
	"FISCAL_RECEIPT_PRINTED":"FISCAL_RECEIPT_PRINTED",
	"FISCAL_RECEIPT_PRINT_FAILED":"FISCAL_RECEIPT_PRINT_FAILED"
}