var FiscalPrinterEventType = 
{
	"FISCAL_RECEIPT_RECEIVED":"FISCAL_RECEIPT_RECEIVED",
	"FISCAL_RECEIPT_REJECTED":"FISCAL_RECEIPT_REJECTED",
	"FISCAL_RECEIPT_PRINTED":"FISCAL_RECEIPT_PRINTED",
	"FISCAL_RECEIPT_PRINT_FAILED":"FISCAL_RECEIPT_PRINT_FAILED",
	"CONFIGURATION_RECEIVED":"CONFIGURATION_RECEIVED",
	"CONFIGURATION_REJECTED":"CONFIGURATION_REJECTED",
	"CONFIGURATION_WRITTEN":"CONFIGURATION_WRITTEN",
	"CONFIGURATION_WRITE_FAILED":"CONFIGURATION_WRITE_FAILED",
	"CONNECTION_ERROR":"CONNECTION_ERROR",
	"CONNECTION_CLOSE":"CONNECTION_CLOSE"
};