var P3ComEventType =
{
	"DISCOVERY_STARTED": "DISCOVERY_STARTED",
	"HOST_DISCOVERED": "HOST_DISCOVERED",
	"DISCOVERY_FINISHED": "DISCOVERY_FINISHED",
	"COMMAND_ACKNOWLEDGED": "COMMAND_ACKNOWLEDGED",
	"COMMAND_REJECETED": "COMMAND_REJECETED",
	"COMMAND_COMPLETED": "COMMAND_COMPLETED",
	"COMMAND_PROGRESS": "COMMAND_PROGRESS",
	"COMMAND_FAILED": "COMMAND_FAILED",
	"CONNECTION_ERROR": "CONNECTION_ERROR",
	"CONNECTION_CLOSE": "CONNECTION_CLOSE"
};