var ScannerEventType =
{
	"LOAD_SCANNERS_RECEIVED":"LOAD_SCANNERS_RECEIVED",
	"LOAD_SCANNERS_REJECETED":"LOAD_SCANNERS_REJECETED",
	"SCANNER_LIST_LOADED":"SCANNER_LIST_LOADED",
	"LOAD_SCANNERS_FAILED":"LOAD_SCANNERS_FAILED",
	"SCAN_DOCUMENT_RECEIVED":"SCAN_DOCUMENT_RECEIVED",
	"SCAN_DOCUMENT_REJECETED":"SCAN_DOCUMENT_REJECETED",
	"DOCUMENT_SCANNED":"DOCUMENT_SCANNED",
	"SCAN_DOCUMENT_FAILED":"SCAN_DOCUMENT_FAILED",
	"CONNECTION_ERROR":"CONNECTION_ERROR",
    "CONNECTION_CLOSE":"CONNECTION_CLOSE"
};
