var ScanProperties = function () {
    this.filepath = undefined; //string
    this.deviceName = undefined;
    this.name = undefined; // string
    this.extension = undefined; // int
    this.deviceId = undefined; // string
    this.isAdf = undefined; // bool
    this.isDuplex = undefined; // bool
    this.TransferAllPages = undefined; // bool
    this.SCAN_COLOR_MODE = undefined; // int
    this.HORIZONTAL_SCAN_RESOLUTION_DPI = undefined; //  int
    this.VERTICAL_SCAN_RESOLUTION_DPI = undefined; //  int
    this.HORIZONTAL_SCAN_START_PIXEL = undefined; //  int
    this.VERTICAL_SCAN_START_PIXEL = undefined; //  int
    this.HORIZONTAL_SCAN_SIZE_PIXELS = undefined; //  int
    this.VERTICAL_SCAN_SIZE_PIXELS = undefined; //  int
    this.SCAN_BRIGHTNESS_PERCENTS = undefined; //  int
    this.SCAN_CONTRAST_PERCENTS = undefined; //  int
};